DFE-Digital/check-an-early-years-qualification

.github/actions/build-dotnet-app/action.yml
src/Dfe.EarlyYearsQualification.Web/Controllers/HomeController.cs
src/Dfe.EarlyYearsQualification.Web/Views/Home/Privacy.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml

Removed the Privacy page as not needed.
PR also used to test the PR workflow.
Running locally.
N/A

Removed the Privacy page.

---

.github/actions/run-e2e-tests/action.yml
.github/workflows/code-pr-check.yml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress.config.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/dummy-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/fixtures/example.json
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/support/commands.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/support/e2e.js
tests/Dfe.EarlyYearsQualification.E2ETests/package-lock.json
tests/Dfe.EarlyYearsQualification.E2ETests/package.json

Initial commit of the Cypress project & tests. Updated workflow to add in Cypress run.
Running the dummy cypress tests locally.

Initial commit of the Cypress project & tests

---

terraform/azure-remote-state/main.tf

Updated the storage account name to bring it under 24 characters
Running the script within Azure

Updated the storage account name to bring it under 24 characters

---

.github/workflows/code-pr-check.yml

Updated workflow action to only run code quality step on pull requests

Updated workflow action to only run code quality step on pull requests

---

src/Dfe.EarlyYearsQualification.Content/Entities/NavigationLink.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs
src/Dfe.EarlyYearsQualification.Content/Services/IContentService.cs
src/Dfe.EarlyYearsQualification.Web/Extensions/AddMockContentful.cs
src/Dfe.EarlyYearsQualification.Web/ViewComponents/FooterLinksViewComponent.cs
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Components/FooterLinks/Default.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Footer.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Header.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/_ViewImports.cshtml
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/ViewComponents/FooterLinksViewComponentTests.cs

Initial commit of the FootLinks component to allow new links to be dynamically added through the CMS
Creating an Entry in the CMS and running locally. Unit Tests added for the View Component.

EYQB-5 Add Dynamic Footer Links

---

.github/workflows/tf-azure-deploy.yml
terraform/azure-network/key-vault.tf
terraform/azure-network/outputs.tf
terraform/local.tf
terraform/variables.tf

Initial commit of the terraform deploy workflow
N/A - workflow

EYQB-65 initial commit of the terraform deploy workflow

---

terraform/azure-network/key-vault.tf

EYQB-65 Added the GH keyvault access policy
N/A - workflow update

EYQB-65 Added the GH keyvault access policy

---

terraform/azure-network/key-vault.tf

Commented out the contentful secret placeholders
N/A - IaC script update

EYQB-65 commented out the contentful secret placeholders

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Program.cs
src/Dfe.EarlyYearsQualification.Web/appsettings.json

Added KeyVault packages and blank endpoint into appSettings.

Added KeyVault packages and blank endpoint into appSettings.

---

.github/workflows/main-build-and-deploy.yml
terraform/local.tf

Update deploy permissions

---

terraform/azure-web/web-app.tf
terraform/local.tf

Updated the web app to add identity

Updated the web app to add identity

---

terraform/azure-web/web-app.tf

Updated the object id

---

adr/0000-template.md
adr/0001-web-framework.md
adr/0002-application-framework.md
adr/0003-build-test-deploy-environment.md
adr/0004-hosting-platform.md
adr/0005-source-repository.md
adr/0006-deployment-tooling.md
adr/0007-infrastructure-as-code.md
adr/0008-container-registry.md
adr/0009-secrets-management.md
adr/0010-content-management.md
adr/README.md

Documentation for log architectural decisions.
Manual check of each file for formatting issues.

EYQB: Architectural Decision Logs

---

adr/0011-tools-for-creating-unit-tests.md
adr/0012-tools-for-creating-ui-tests.md
adr/README.md

Added documents for unit and ui testing
N/A - Documentation
N/A

Added documents for unit and ui testing

---

.github/actions/run-app-for-testing/action.yml
.github/actions/run-e2e-tests/action.yml
src/Dfe.EarlyYearsQualification.Web/Controllers/HealthController.cs

Created a health controller and updated a couple of the action
N/A

Created a health controller and updated a couple of the action

---

.github/actions/run-e2e-tests/action.yml
.github/workflows/code-pr-check.yml
tests/Dfe.EarlyYearsQualification.E2ETests/package-lock.json
tests/Dfe.EarlyYearsQualification.E2ETests/package.json

Updated to add the Firefox tests back in following the cypress update
N/A
N/A

Updated to add the Firefox tests back in following the cypress update

---

src/Dfe.EarlyYearsQualification.Content/Extensions/HtmlRendererExtensions.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/Heading1Renderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/Heading3Renderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/Heading4Renderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/Heading5Renderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/Heading6Renderer.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/HomeController.cs

Added additional renderers and minor refactors

Added additional renderers and minor refactors

---

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs
src/Dfe.EarlyYearsQualification.Content/Entities/GovUkInsetText.cs
src/Dfe.EarlyYearsQualification.Content/Extensions/HtmlRendererExtensions.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/GovUkInsetTextRenderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/GovUkParagraphRenderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/Helpers/NestedContentHelper.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs
src/Dfe.EarlyYearsQualification.Content/Services/IContentService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Extensions/AddMockContentful.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationDetailsModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs

- Pulled out all hard coded content into Contentful
- Added renderer functionality to facilitate this
Manually tested locally

Details Page Refactor into Contentful

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Header.cshtml

Updated to fix warnings and remove redundant code

Updated to fix warnings and remove redundant code

---

README.md
src/Dfe.EarlyYearsQualification.Web/Program.cs
src/Dfe.EarlyYearsQualification.Web/appsettings.json

Updated to allow keyvault secrets to be pulled in when running locally

Updated to allow keyvault secrets to be pulled in when running locally

---

.github/workflows/build-image.yml
.github/workflows/main-build-and-deploy.yml
.github/workflows/tf-azure-deploy.yml
terraform/local.tf

- Added code to deploy web app out to staging
- Enabled staging terraform plan and apply
- Added env var to terraform to point staging at preview contentful
EYQB-108
Staging env can be seen here:
https://staging.check-an-early-years-qualification.education.gov.uk/
- [N/A] I have added tests (Unit, E2E) that prove my fix is effective or that my feature works
- [N/A] Any dependent changes have been merged and published in downstream modules

Code to enable staging deployment

---

src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Question.cshtml

Temporary removal to test staging environment

Removed anti forgery token temporarily

---

.github/dependabot.yml

Updated dependabot config to add in npm package checks
N/A - workflow change
N/A

Updated to add in npm package checks

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Program.cs
src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js

Initial commit of the security header changes
Before:
After:

Initial commit of the security header changes

---

tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.json

Updated to add in the new pages to the pa11y config file

Updated to add in the new pages to the pa11y config file

---

src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs

Updated to add frame ancestor for contentful to allow it to work in live preview
Please describe the tests that you ran to verify your changes.

Updated to add frame ancestor for contentful

---

src/Dfe.EarlyYearsQualification.Content/Constants/AdvicePages.cs
src/Dfe.EarlyYearsQualification.Content/Constants/QuestionPages.cs
src/Dfe.EarlyYearsQualification.Content/Entities/GovUkInsetText.cs
src/Dfe.EarlyYearsQualification.Content/Entities/QuestionPage.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/GovUkInsetTextRenderer.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs
src/Dfe.EarlyYearsQualification.Web/Constants/Options.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Extensions/AddMockContentful.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModel.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs

Address some ReSharper suggestions
All tests pass locally, pages look fine.

Address some ReSharper suggestions

---

terraform/main.tf

Updated formatting of the terraform file

Updated formatting

---

.github/workflows/terraform-pr-check.yml
terraform/azure-web/web-app.tf

initial commit of the terraform format check workflow
N/A
N/A

Initial commit of the terraform format check workflow

---

terraform/local.tf

Updated the app settings to see if this helps to resolve the slow docker startups
N/A
N/A

Updated the app settings

---

.github/workflows/code-pr-check.yml

Updated the workflow to ensure it runs for adr and terraform
N/A
N/A

Updated the workflow to ensure it runs for adr and terraform

---

.github/actions/run-unit-tests/action.yml
.github/dependabot.yml

Updated the action to add in message
N/A
N/A

Updated the action to add in message

---

.github/actions/run-unit-tests/action.yml

Updated the if statements on the steps to check it's not dependabot

Updated the if statements on the steps to check it's not dependabot

---

src/Dfe.EarlyYearsQualification.Web/Views/Cookies/Index.cshtml

Provide a closing fieldset tag.
n/a
Runs locally, pages look fine.

Close fieldset tag

---

terraform/azure-network/key-vault.tf

EYQB-223: Updated gh access policy

---

terraform/azure-network/key-vault.tf

EYQB-223: Updated permissions

---

terraform/main.tf

Updated to add in the missing variable

Updated to add in the missing variable

---

src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.json
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/question-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs

Initial commit of the changes to add in the When was the qualification started question page

EYQB-238: Initial commit of the new question page

---

src/Dfe.EarlyYearsQualification.Content/Constants/QuestionPages.cs
src/Dfe.EarlyYearsQualification.Content/Entities/QuestionPage.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/GovUk/UnorderedListRenderer.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Question.cshtml
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.json
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/question-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/security-header-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Initial commit of the new 'what level is the qualification' question
Running locally, unit test and e2e tests

EYQB-239: initial commit of the new question page

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Program.cs

Added new robots.txt middleware

Updated to add in robots.txt

---

terraform/main.tf
terraform/modules/azure-web/README.md
terraform/modules/azure-web/app-gateway.tf
terraform/modules/azure-web/variables.tf

- updated terraform to add an exclude to the app gateway for the new preferences cookie
To be tested once in main

new terraform exclude

---

.github/workflows/build-image.yml

removed git hash from docker build action

---

.github/workflows/build-image.yml

reverted work on contentful secrets

---

.github/workflows/tf-azure-deploy.yml
terraform/README.md
terraform/local.tf
terraform/main.tf
terraform/modules/azure-network/README.md
terraform/modules/azure-network/key-vault.tf
terraform/modules/azure-network/variables.tf
terraform/variables.tf

- Added 3 secrets and one variable to TF variables
- Secrets are being added to KV
- Variable is being utilised as an env var to set use of preview API or not
- Also removed unnecessary step in TF deploy which raises an incident that required approval
https://dfedigital.atlassian.net/browse/EYQB-243
Will run TF deploy post merge

added Contentful secrets and settings to terraform

---

terraform/modules/azure-network/key-vault.tf

added recover to the github action secrets permissions

---

.github/workflows/main-build-and-deploy.yml

Initial commit of the deployment slot deployments. This is still a WIP as I want to test this works on Development before adding it to Staging. This will be done by extracting it out to an action to be reused by multiple environments
N/A
N/A

EYQB-233: Initial commit of the deployment slot deployments

---

terraform/modules/azure-web/README.md
terraform/modules/azure-web/web-app.tf

Updated terraform file
N/A
N/A

EYQB-233: Updated terraform file

---

terraform/README.md
terraform/main.tf
terraform/modules/azure-web/README.md
terraform/modules/azure-web/variables.tf
terraform/modules/azure-web/web-app.tf
terraform/variables.tf

Updated the slot data resource
N/A
N/A

EYQB-233: Updated the slot data resource

---

terraform/modules/azure-web/web-app.tf

Updated to fix slot name
N/A
N/A

EYQB-233: Updated to fix slot name

---

terraform/modules/azure-web/README.md
terraform/modules/azure-web/web-app.tf

Comment out the slot access policy
N/A
N/A

EYQB-233: Comment out the slot access policy

---

terraform/modules/azure-web/README.md
terraform/modules/azure-web/web-app.tf

Updated to add in the access policy for the slot
N/A
N/A

Updated to add in the access policy for the slot

---

.github/workflows/main-build-and-deploy.yml

Updated workflow to add loop to curl command
N/A
N/A

EYQB-233: Updated workflow to add loop to curl command

---

.github/workflows/main-build-and-deploy.yml

Updated the deployment pipeline
N/A
N/A

EYQB-233: Updated the deployment pipeline

---

.github/workflows/main-build-and-deploy.yml

EYQB-233: Added checkout step

---

adr/0009-secrets-management.md
adr/0011-tools-for-creating-unit-tests.md
adr/0014-c-sharp-coding-standards.md
adr/0015-cookie-policy.md
adr/0016-terraform-docs.md
adr/0017-access-guard-in-pilot.md
adr/README.md

ADRs introduced for recent decisions.

Create ADRs for recent decisions

---

terraform/main.tf
terraform/modules/azure-web/README.md
terraform/modules/azure-web/app-gateway.tf
terraform/modules/azure-web/variables.tf

Added new user journey cookie to exclusion list, letting it through the app gateway

---

.github/actions/run-unit-tests/action.yml

Updated the min code coverage value
N/A
N/A

Updated the min code coverage value

---

.github/workflows/code-pr-check.yml
.github/workflows/dev-security-check.yml

Initial POC for adding ZAP proxy. 

EYQB-339: Initial POC for adding ZAP proxy. 

---

src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/advice-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/urls-to-check.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs

Updated to wire up the qual 2 between 1 sep 14 and 31 aug 19

Updated to wire up the qual 2 between 1 sep 14 and 31 aug 19

---

src/Dfe.EarlyYearsQualification.Content/Entities/QualificationListPage.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentFilterService.cs
src/Dfe.EarlyYearsQualification.Content/Services/IContentFilterService.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulFilterService.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/BasicQualificationModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/FilterModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationDetailsModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationListModel.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/IUserJourneyCookieService.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Header.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/back-button-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-list-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/urls-to-check.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulFilterServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentFilterServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs

Initial commit of the qualification list page.
Please describe the tests that you ran to verify your changes.

Initial commit of the qualification list page

---

src/Dfe.EarlyYearsQualification.Web/Helpers/GtmConfiguration.cs
src/Dfe.EarlyYearsQualification.Web/Program.cs
src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml
src/Dfe.EarlyYearsQualification.Web/appsettings.json
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/google-analytics.js
terraform/README.md
terraform/local.tf
terraform/variables.tf
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/security-header-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Helpers/GtmConfigurationTests.cs

Added in GtmConfiguration helper

EYQB-340: Added in GtmConfiguration helper

---

src/Dfe.EarlyYearsQualification.Content/Entities/CheckAdditionalRequirementsPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/CheckAdditionalRequirementsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/AdditionalRequirementQuestionModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/CheckAdditionalRequirementsPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/CheckAdditionalRequirements/Index.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/back-button-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/check-additional-questions-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/CheckAdditionalRequirementsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Updated to add in the error summary list and show the error message per question

EYQB-365: Updated to add in the error summary list

---

src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/security-header-spec.cy.js

Updated to add in the gtag csp header
N/A

EYQB-469: Updated to add in the gtag csp header

---

src/Dfe.EarlyYearsQualification.Web/Views/Advice/Advice.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Date.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Dropdown.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Radio.cshtml

Updated the page titles to show differently in tracking
Running locally 
N/A

EYQB-469: Updated the page titles to show differently in tracking

---

terraform/main.tf
terraform/modules/azure-storage/README.md
terraform/modules/azure-storage/storage.tf
terraform/modules/azure-storage/variables.tf

Added missing secret containing storage account connection string.
EYQB-345

Added storage account connection string secret.

---

terraform/README.md
terraform/local.tf
terraform/variables.tf

Removed tracking id as no longer needed
N/A
N/A

Removed tracking id as no longer needed

---

src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css

Added a skip to main content link

Added a skip to main content link

---

src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs

now using qualification level instead of the user selected level on the your results page

---

src/Dfe.EarlyYearsQualification.Content/Entities/DateQuestionPage.cs
src/Dfe.EarlyYearsQualification.Content/Entities/DropdownQuestionPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/AdditionalInformationModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/BaseQuestionModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/RadioQuestionModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Date.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Dropdown.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Radio.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/AdditionalInformation.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/question-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Updated the content models so that questions have the optional additional information section
Running locally & e2e tests

Updated the content models to add additional information section

---

src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs

fix for the additional requirements checks not matching up questions to answers properly

---

.github/workflows/sonarcloud.yml
src/Dfe.EarlyYearsQualification.Web/Filters/ChallengeResourceFilterAttribute.cs

Second attempt at getting SonarCloud to analyse a PR.
I _think_ this will cause SonarCloud to do a full analysis in `main` when it's committed, and an incremental analysis in any PR wanting to commit into `main`.

Workflow for SonarCloud to analyse PRs

---

src/Dfe.EarlyYearsQualification.Web/Views/CheckAdditionalRequirements/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/ConfirmQualification/index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Date.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Dropdown.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Radio.cshtml

Minor spacing updates following review with Laura

Minor spacing updates

---

src/Dfe.EarlyYearsQualification.Content/Constants/AdvicePages.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/GovUk/Heading4Renderer.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/RatioRow.cshtml
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/advice-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/urls-to-check.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Renderers/Heading4RendererTests.cs

Updated to add in the new advice pages for L6
Running locally, unit tests and e2e test

EYQB-485: Updated to add in the new advice pages for L6

---

src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/AdditionalRequirementAnswerModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationDetailsModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-details-spec.cy.js

- Added dynamic section to the details section of the results page listing the questions for said qualificaiton as well as the answer(s) the user has submit
- Refactor of controller action for this view
https://dfedigital.atlassian.net/browse/EYQB-376
- Existing unit tests passing with no changes needed from the refactor
- New section of E2E page test added and passing along with existing tests passing

Added additional requirements questions and answers to the your result page

---

tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Renderers/NestedContentHelperTests.cs

Added additional unit tests
Running unit tests

Added additional unit tests

---

src/Dfe.EarlyYearsQualification.Web/Views/Home/Index.cshtml

Updated to make the related content conditionally render
Please describe the tests that you ran to verify your changes.

EYQB-379: Updated to make the related content conditionally render

---

src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentFilterService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/IUserJourneyCookieService.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentFilterServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs

Initial commit of the search functionality bug fixes

Initial commit of the search functionality bug fixes

---

src/Dfe.EarlyYearsQualification.Web/Views/CheckAdditionalRequirements/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml

- Small HTML changes to the additional reqs page
- Layout change to the qualification list page to bring 'clear search' button more in line with the designs
- Manual check with resizing window reasonably
- New and existing tests passing
Before:
After:

Styling changes to the additional reqs page and the qualification list page

---

src/Dfe.EarlyYearsQualification.Content/Renderers/GovUk/ExternalNavigationLinkRenderer.cs
src/Dfe.EarlyYearsQualification.Content/Renderers/GovUk/PhaseBannerRenderer.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Mock/Helpers/ContentfulContentHelper.cs
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/phase-banner-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Renderers/ExternalNavigationLinkRendererTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Renderers/PhaseBannerRendererTests.cs

See the PR title.
https://dfedigital.atlassian.net/browse/EYQB-484
- Manually tested locally
- Modified existing test setup - existing tests passing

added external link renderer to phase banner renderer to support new content

---

src/Dfe.EarlyYearsQualification.Web/Views/Error/NotFound.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/not-found-page-spec.cy.js

added mailto href to 404 page

---

src/Dfe.EarlyYearsQualification.Web/Views/Questions/Date.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Dropdown.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Questions/Radio.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/gtm/form-handler.js

Added new form handler js data layer changes to push events to GA

EYQB-467: Added new form handler data layer changes to push events to GA

---

src/Dfe.EarlyYearsQualification.Web/Controllers/ChallengeController.cs
src/Dfe.EarlyYearsQualification.Web/Program.cs

EYQB-516: Updated cookie secure flag

---

src/Dfe.EarlyYearsQualification.Web/Program.cs

Changed logic to set to Always once deployed

EYQB-516: Changed logic to set to Always once deployed

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-list-spec.cy.js

Removed fields, tweaked the styling of the chevron and updated e2e tests.

EYQB-396: Removed fields

---

src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css

Increased the margin on the link

EYQB-396: Updated margin

---

src/Dfe.EarlyYearsQualification.Content/Entities/ConfirmQualificationPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/ConfirmQualificationController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/ConfirmQualificationPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/ConfirmQualification/index.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/confirm-qualification-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ConfirmQualificationControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Updated to remove some fields and added new ones

EYQB-390: Updated to remove some fields and added new ones

---

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/DetailsPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationDetailsModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-details-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Updated the qualification results page to restructure content

EYQB-495: Updated the qualification results page to restructure content

---

src/Dfe.EarlyYearsQualification.Web/Views/Error/NotFound.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/not-found-page-spec.cy.js

Update not found page to add tech support email address.
Running locally and e2e test

EYQB-526: Update not found page to add tech support email address

---

src/Dfe.EarlyYearsQualification.Web/Views/Error/NotFound.cshtml

EYQB-526: Added class to link

---

src/Dfe.EarlyYearsQualification.Web/Views/CheckAdditionalRequirements/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml

Removed qualification Id from page titles

EYQB-519: Removed qualification Id from page titles

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/RatioRow.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css

UI tweaks for mobile
Qual details page
Desktop:
Mobile:
Select qualification page
Desktop:
Mobile:

EYQB-525: fix mobile styling

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js

Added new cookie to header to ensure all pages can be checked and fixed accessibility issue with the print button
Please describe the tests that you ran to verify your changes.

Added new cookie to header to ensure all pages can be checked

---

src/Dfe.EarlyYearsQualification.Web/Views/Home/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/gtm/form-handler.js

EYQB-531: Updated to add new events

---

terraform/modules/azure-storage/storage.tf

Reenable SASs for storage account for now.
EYQB-513

Reenable SASs for now.

---

terraform/modules/azure-web/app-gateway.tf

EYQB-520: Added new exclusion

---

src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentFilterService.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentFilterServiceTests.cs

Increased the filter limit
N/A

Increased the filter limit

---

tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js

Pa11y config use const not var.
EYQB-568
Locally.

Use const not var.

---

.github/actions/run-smoke-tests/action.yml
.github/workflows/main-build-and-deploy.yml
tests/Dfe.EarlyYearsQualification.SmokeTests/cypress.config.js
tests/Dfe.EarlyYearsQualification.SmokeTests/cypress/e2e/smoke-test-spec.cy.js
tests/Dfe.EarlyYearsQualification.SmokeTests/cypress/support/commands.js
tests/Dfe.EarlyYearsQualification.SmokeTests/cypress/support/e2e.js
tests/Dfe.EarlyYearsQualification.SmokeTests/package-lock.json
tests/Dfe.EarlyYearsQualification.SmokeTests/package.json

New smoke tests and github workflow changes
Running smoke test locally
N/A

EYQB-650: New smoke tests and github workflow changes

---

src/Dfe.EarlyYearsQualification.Web/wwwroot/js/clarity/head-script.js
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/gtm/head-script.js

Updated the variables in the scripts to stop conflicts

EYQB-660: Updated the variables in the scripts to stop conflicts

---

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs
src/Dfe.EarlyYearsQualification.Content/Entities/FeedbackBanner.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/Base/ServiceController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/AdvicePageModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/DetailsPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/FeedbackBannerModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/Advice/Advice.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/FeedbackBanner.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/advice-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ServiceControllerTests.cs

Added feedback banner component
Run locally, unit tests and e2e tests

EYQB-656: Added feedback banner component

---

src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/FeedbackBanner.cshtml

Wrapped the feedback container to bring in the margins.
Locally

EYQB-656: Minor UI tweak

---

src/Dfe.EarlyYearsQualification.Content/Constants/AdvicePages.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/advice-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Added the temporary privacy poicy advice page

EYQB-687: Added the temporary privacy poicy advice page

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml

Small formatting change
https://dfedigital.atlassian.net/jira/software/projects/EYQB/boards/216?selectedIssue=EYQB-647
Existing tests passing
Visual check against current staging to make sure the look is the same
Current Staging:
Proposed Change:

Changed 'your search' heading back to regular H2

---

.github/workflows/development-build-and-deploy.yml

Updated to allow chore branches to be deployed to dev

Updated to allow chore branches to be deployed to dev

---

.github/workflows/development-build-and-deploy.yml

Updated workflow

---

.github/workflows/development-build-and-deploy.yml

Changed the if statement

---

.github/workflows/build-image.yml

Format branch name as tags cannot contain /

---

.github/workflows/development-build-and-deploy.yml
.github/workflows/release-build-and-deploy.yml

Minor tweaks to the workflows to fix a number of small issues

---

terraform/modules/azure-web/web-app.tf

Fix for dev terraform - removing slot for dev

---

.github/workflows/release-build-and-deploy.yml

Updated the workflow to pass webapp_url to health check

---

.github/workflows/tf-azure-deploy.yml
terraform/main.tf
terraform/modules/azure-storage/storage.tf
terraform/modules/azure-storage/variables.tf
terraform/modules/azure-web/web-app.tf
terraform/variables.tf

Allow network access from GitHub runner's IP address to storage account to allow setting network access.
EYQB-534
Terraform deployment runs on PR in `dev` environment.

Set the current IP address in env

---

.github/workflows/development-build-and-deploy.yml
.github/workflows/release-build-and-deploy.yml

Removed the branch check as this has been replaced with the branch protection rules on the environments

Removed the branch check from workflows

---

README.md

Status badges on the README page.

Status badges on README

---

.github/workflows/dev-security-check.yml
.github/workflows/sonarcloud.yml
README.md

Some changes to workflows to reflect the new process and different branch naming strategy.

Workflow changes

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj

Updated to latest nuget packages

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Program.cs

Added app insights package
Pushed to dev environment and seeing logs coming through

Added app insights package

---

.github/workflows/restart-service.yml

Create a GitHub workflow to restart the service.

Create workflow to restart service

---

.github/workflows/tf-azure-deploy.yml

Remove the need to upload plan artifacts

---

LICENSE
src/Dfe.EarlyYearsQualification.Web/appsettings.json

Add license

---

.github/workflows/tf-azure-deploy.yml

Updated TF path in the apply step. Added the action to the run-name so we can see what option was selected for the run

Updated TF path in the apply step

---

.github/workflows/restart-service.yml
.github/workflows/tf-azure-deploy.yml

Updated to add in the restart workflow to the terraform deploy workflow

Updated to add in the restart workflow to the terraform deploy workflow

---

.github/workflows/terraform-pr-check.yml
.github/workflows/tf-azure-deploy.yml
terraform/main.tf
terraform/modules/azure-alerts/alerts.tf
terraform/modules/azure-alerts/variables.tf
terraform/modules/azure-web/outputs.tf

Updated to add in the new alerts to test setup

---

terraform/main.tf
terraform/modules/azure-alerts/README.md
terraform/modules/azure-alerts/alerts.tf
terraform/modules/azure-alerts/variables.tf

Added in the new activity log alerts.
Deployed to staging and triggered load test

Initial commit of the activity log alert

---

src/Dfe.EarlyYearsQualification.Content/Dfe.EarlyYearsQualification.Content.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj

Updated packages to latest versions

Updated packages to latest versions

---

src/Dfe.EarlyYearsQualification.Content/Entities/Qualification.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockQualificationsRepository.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/ConfirmQualificationController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ConfirmQualificationControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs

Updated to add in new flag to allow certain qualifications to automatically be approved at L6
Running locally and unit test

Updated to add in new flag to allow certain qualifications to automatically be approved at L6

---

src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/RatioRow.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-details-spec.cy.js

Not approved label
Running unit tests and e2e tests

EYQB-740: Not approved label

---

.github/workflows/code-pr-check.yml
.github/workflows/dev-security-check.yml

Update workflow versions

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/security-header-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Setup/SecureHeaderConfigurationTests.cs

Updated packages to latest version and updated unit test as part of the OwaspHeaders.Core update which changed the default value (https://github.com/GaProgMan/OwaspHeaders.Core/blob/main/changelog.md#version-91)

Updated packages to latest version

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Setup/SecureHeaderConfigurationTests.cs

Updated packages and fixed breaking changes

Updated packages and fixed breaking changes

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Views/Challenge/EntryForm.cshtml

Updated nuget package version and fixed deprecated warning

Updated nuget package version and fixed deprecated warning

---

src/Dfe.EarlyYearsQualification.Content/Constants/AdvicePages.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/IUserJourneyCookieService.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/advice-spec.cy.js
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/urls-to-check.js
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs

Added new advice pages for level 7 qualifications depending on date
Added new e2e tests to test the new journey, adjusted tests for previous level 7 page. 
New unit tests to test the new actions
Manual testing

feature: added new level 7 advice pages

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/security-header-spec.cy.js
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Setup/SecureHeaderConfigurationTests.cs

Updated packages to the latest version
Running unit tests
N/A

Updated packages to the latest version

---

src/Dfe.EarlyYearsQualification.Web/Attributes/RedirectIfDateMissingAttribute.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Attributes/RedirectIfDateMissingAttributeTests.cs

Fixed missing country value

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationSearch/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css

Initial commit of the changes to change content and add new styling
Desktop:
Tablet:
Mobile:

Initial commit of the changes to change content and add new styling

---

tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationSearchServiceTests.cs

Be explicit: we're testing the class not the interface.
All unit & end-to-end tests pass.

Adopt SonarCloud suggestion.

---

src/Dfe.EarlyYearsQualification.Content/Dfe.EarlyYearsQualification.Content.csproj
src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj

Updated to the latest packages

Updated to the latest packages

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
src/Dfe.EarlyYearsQualification.Web/Program.cs
src/Dfe.EarlyYearsQualification.Web/Services/Cookies/CookieManager.cs
src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml

Removed robots package and added meta tags

EYQB-820: Removed robots package and added meta tags

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationSearch/Get.cshtml

added aria role as requested by accessibility audit
Does generate a new warning but it's sonar cloud being over zealous
##EYQB-840
https://dfedigital.atlassian.net/browse/EYQB-840
All e2e tests passing.

chore: added aria role as requested by accessibility audit

---

.github/workflows/cycle-storage-account-access-keys.yml

Added new workflow to test cycling the SA keys
Running the workflow against the dev env.

EYQB-533: Added new workflow to test cycling the SA keys

---

.github/actions/run-playwright-e2e-tests/action.yml
tests/Dfe.EarlyYearsQualification.E2ETests/package-lock.json
tests/Dfe.EarlyYearsQualification.E2ETests/package.json
tests/Dfe.EarlyYearsQualification.E2ETests/playwright.config.ts

Updated the playwright packages to latest version and updated to headless chromium
Running tests locally (both UI & headless)

Updated the playwright packages

---

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/DetailsPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationResultModel.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/IQualificationDetailsService.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/QualificationResult.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/qualification-details.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationDetailsServiceTests.cs

Initial commit of the new qualification result component
F&R
Not F&R at L3
Not F&R

EYQB-796: Qualification result component

---

.github/workflows/automated-storage-account-access-keys-rotation.yml

Updated workflow to add permissions
N/A
N/A

EYQB-533: Updated workflow to add permissions

---

src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/package-lock.json
tests/Dfe.EarlyYearsQualification.E2ETests/package.json
tests/Dfe.EarlyYearsQualification.E2ETests/playwright.config.ts

updated styling to reduce to two thirds width
Running locally & running e2e tests

EYQB-846: updated styling to reduce to two thirds width

---

.github/workflows/automated-storage-account-access-keys-rotation.yml
.github/workflows/cycle-storage-account-access-keys.yml

Added workflow dispatch to be able to trigger workflow to test
N/A
N/A

Added workflow dispatch to be able to trigger workflow to test

---

.github/workflows/automated-storage-account-access-keys-rotation.yml

Updated to test auto approve
N/A
N/A

EYQB-533: Updated to test auto approve

---

.github/workflows/automated-storage-account-access-keys-rotation.yml
adr/0021-storage-account-key-rotation.md
adr/README.md

Added a sleep to allow approvals to be created
N/A
N/A

EYQB-533: Added a sleep to allow approvals to be created

---

.github/workflows/automated-storage-account-access-keys-rotation.yml

Changed token and updated timings
N/A
N/A

EYQB-533: Changed token and updated timings

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj

Updated nuget packages
Unit & E2E tests

Updated nuget packages

---

src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs

Tiny fix to typo in code.
All unit tests pass.

Use logical && rather than bitwise &

---

src/Dfe.EarlyYearsQualification.Content/Entities/QualificationListPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/FilterModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationListModel.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationSearch/QualificationSearchService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationSearch/Get.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/qualification-list.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationSearchServiceTests.cs

Initial commit of the page redesign changes

EYQB-848: Initial commit of the page redesign changes

---

src/Dfe.EarlyYearsQualification.Content/Entities/DatesQuestionPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/DateQuestionModelValidator.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/DatesValidationResult.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/IDateQuestionModelValidator.cs
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/question.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/DateQuestionModelValidatorTests.cs

Added validation errors for if the user enters an earlier awarded date than started
Manual testing, Unit tests and new e2e test

feature: added validation for awarded date before start date

---

tests/Dfe.EarlyYearsQualification.SmokeTests/playwright/tests/smoke-tests.spec.ts

Updated smoke test identifiers
N/A

Updated smoke test identifiers

---

src/Dfe.EarlyYearsQualification.Content/Constants/AdvicePages.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/advice.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/shared/urls-to-check.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Initial commit of the help advice page
Running locally, unit & e2e tests

EYQB-913: Initial commit of the help advice page

---

src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Mappers/AdvicePageMapper.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationNotOnListPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/Advice/QualificationNotOnList.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/QualificationSearch/Get.cshtml
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/gtm/form-handler.js
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/pages/qualification-details-page.js
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/pages/qualification-not-on-list-page.js
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/pages/search-results-page.js

EYQB-896: GTM Updates

---

src/Dfe.EarlyYearsQualification.Web/Controllers/ChallengeController.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ChallengeControllerTests.cs

Release branch:
- challenge page redirect to start page if public access
Tested in development while in feature PRs.

Release 20 March 2025

---

.github/workflows/tf-azure-deploy.yml
terraform/azure-remote-state/main.tf
terraform/main.tf
terraform/modules/azure-alerts/alerts.tf
terraform/modules/azure-network/vnet.tf
terraform/modules/azure-storage/storage.tf
terraform/modules/azure-web/app-gateway.tf
terraform/modules/azure-web/web-app.tf
terraform/terraform.tf

Change to latest Terraform, and specify values that were previously defaults.
Part of EYQB-943
Tested in lower environments. Always validate with `terraform plan` before running `apply`.

Update to latest Terraform

---

src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationSearchController.cs
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js
tests/Dfe.EarlyYearsQualification.E2ETests/tests/journey/back-button.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/journey/journey.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/check-additional-questions.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/qualification-list.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/shared/playwrightWrapper.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/shared/urls-to-check.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ConfirmQualificationControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs

Qualification URL change PR 2

---

adr/0012-tools-for-creating-ui-tests.md
adr/0023-changed-tools-for-creating-ui-tests.md
adr/README.md

Update playwright adr

---

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Mappers/QualificationDetailsMapper.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/DetailsPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/QualificationDetailsMapperTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationDetailsServiceTests.cs

Initial commit of the removal of old fields
Running locally, unit tests and E2E tests

Initial commit of the removal of old fields

---

terraform/modules/azure-web/README.md
terraform/modules/azure-web/web-app.tf

Add permission to access Redis cache to App Service green slot's managed identity.
EYQB-987

Grant Redis permission to slot

---

.github/actions/restart-app-service/action.yml
.github/workflows/restart-service.yml
.github/workflows/tf-azure-deploy.yml

Refactored the workflows to use new action
N/A

Refactored the workflows to use new action

---

terraform/variables.tf

Remove redundant terraform variable.
Run on `dev` and `test`/staging.

Variable no longer used

---

src/Dfe.EarlyYearsQualification.Web/Attributes/RedirectIfDateMissingAttribute.cs
tests/Dfe.EarlyYearsQualification.E2ETests/tests/journey/date-missing-redirect.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Attributes/RedirectIfDateMissingAttributeTests.cs

Updated the redirect route to point to  start-new
E2E tests and running locally

Updated the redirect route to point to  start-new

---

src/Dfe.EarlyYearsQualification.Content/Entities/RatioRequirement.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockQualificationsRepository.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/RatioRequirementModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/QualificationApprovalStatus.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/IQualificationDetailsService.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/RatioRow.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/qualification-details.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/ContractResolvers/EntityResolverTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationDetailsServiceTests.cs

Added level 3 EBR ratio details and new Possible Route Available tag
##[EYQB-1054](https://dfedigital.atlassian.net/browse/EYQB-1054)
Manual testing, new e2e tests and unit tests. All existing tests function

Experience-based route information under level 3 on the results page

---

src/Dfe.EarlyYearsQualification.Content/Entities/RatioRequirement.cs
src/Dfe.EarlyYearsQualification.Content/RatioRequirements/BaseRatioRequirement.cs
src/Dfe.EarlyYearsQualification.Content/RatioRequirements/Level2RatioRequirements.cs
src/Dfe.EarlyYearsQualification.Content/RatioRequirements/Level3RatioRequirements.cs
src/Dfe.EarlyYearsQualification.Content/RatioRequirements/Level6RatioRequirements.cs
src/Dfe.EarlyYearsQualification.Content/RatioRequirements/UnqualifiedRatioRequirements.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockQualificationsRepository.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/qualification-details.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockQualificationsRepositoryTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Ratios/RatioRequirementTests.cs
tests/Dfe.EarlyYearsQualification.ValidationChecks/.gitignore
tests/Dfe.EarlyYearsQualification.ValidationChecks/README.md
tests/Dfe.EarlyYearsQualification.ValidationChecks/package-lock.json
tests/Dfe.EarlyYearsQualification.ValidationChecks/package.json
tests/Dfe.EarlyYearsQualification.ValidationChecks/playwright.config.ts
tests/Dfe.EarlyYearsQualification.ValidationChecks/tests/helpers/playwrightWrapper.ts
tests/Dfe.EarlyYearsQualification.ValidationChecks/tests/journey.spec.ts

- EYQB-1051: Contentful field refactor

Release 13 May 25:  Refactor ratio requirements

---

src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
tests/Dfe.EarlyYearsQualification.E2ETests/tests/shared/urls-to-check.ts

Updated to add in missing redirect
Running locally & e2e tests

EYQB-1064: Updated to add in missing redirect

---

src/Dfe.EarlyYearsQualification.Web/Program.cs
src/Dfe.EarlyYearsQualification.Web/Services/HeadHandling/HeadHandlingMiddleware.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/HeadHandlingMiddlewareTests.cs

Added handling of head requests by setting them to gets, processing them, removing the body and then setting the method back to head.
Manually tested a few of the previously failing pages. Seems fine. Added some unit tests to check that values are as expected

feat: added handling of head requests

---

src/Dfe.EarlyYearsQualification.Content/Entities/Qualification.cs
src/Dfe.EarlyYearsQualification.Content/Entities/RatioRequirement.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockQualificationsRepository.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/IQualificationDetailsService.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/qualification-details-ratios.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/shared/playwrightWrapper.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockQualificationsRepositoryTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationDetailsServiceTests.cs

EYQB-1043: Initial commit of the EYITT ratio functionality

---

.github/workflows/run-load-tests.yml
tests/Dfe.EarlyYearsQualification.LoadTests/browser-journey.js
tests/Dfe.EarlyYearsQualification.LoadTests/config/browser-load.json
tests/Dfe.EarlyYearsQualification.LoadTests/config/browser-quick.json
tests/Dfe.EarlyYearsQualification.LoadTests/tests/ncfe-search-journey.js
tests/Dfe.EarlyYearsQualification.LoadTests/tests/recorded-l3-journey.js

Adding load test (against staging) to the pipelines.
EYQB-1076
Tested by running the workflow in GitHub.

EYQB-1076 Load tests in pipeline

---

tests/Dfe.EarlyYearsQualification.ValidationChecks/tests/journey.spec.ts

Added validation tests for some of the new ebr routes

Added validation tests for some possible EBR routes

---

.github/workflows/run-load-tests.yml

Specifying more tightly described crontab schedule.

Update schedule crontab spec

---

src/Dfe.EarlyYearsQualification.Web/wwwroot/js/pages/qualification-details-page.js

Added new event handlers and GTM event

EYQB-1078: Added new event handlers and GTM event

---

src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationDetailsServiceTests.cs

Updated to add in the PossibleRouteAvailable to the switch statement
Unit test & running locally

EYQB-1043: Updated to add in the PossibleRouteAvailable to the switch statement

---

src/Dfe.EarlyYearsQualification.Caching/Dfe.EarlyYearsQualification.Caching.csproj
src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj

Minor package updates
Running locally, e2e & unit tests

Minor package updates

---

tests/Dfe.EarlyYearsQualification.E2ETests/tests/validation/journey.spec.ts
tests/Dfe.EarlyYearsQualification.LoadTests/tests/recorded-l3-journey.js
tests/Dfe.EarlyYearsQualification.LoadTests/tests/support/commonMethods.js

Refactored the load tests and added in the new pre-check page. Also, fixed the validation check tests following the recent journey change tests
Running locally through the quick & load options.

Updated to refactor load tests to make them more maintainable

---

.github/workflows/staging-validation-checks.yml

Added auto approve and checkout step

Added auto approve and checkout step

---

src/Dfe.EarlyYearsQualification.Content/Entities/HelpConfirmationPage.cs
src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs
src/Dfe.EarlyYearsQualification.Web/Mappers/FeedbackComponentMapper.cs
src/Dfe.EarlyYearsQualification.Web/Mappers/FeedbackComponentModelMapper.cs
src/Dfe.EarlyYearsQualification.Web/Mappers/HelpConfirmationPageModelMapper.cs
src/Dfe.EarlyYearsQualification.Web/Mappers/UpDownFeedbackMapper.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/FeedbackComponentModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/HelpConfirmationPageModel.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/UpDownFeedbackModel.cs
src/Dfe.EarlyYearsQualification.Web/Views/Advice/HelpConfirmation.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/FeedbackComponent.cshtml
src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/UpDownFeedback.cshtml
tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js
tests/Dfe.EarlyYearsQualification.E2ETests/tests/_shared/urls-to-check.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/e2e/components/updown-feedback.spec.ts
tests/Dfe.EarlyYearsQualification.E2ETests/tests/e2e/pages/advice.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/AdvicePageMapperTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/FeedbackComponentModelMapperTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/QualificationDetailsMapperTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/UpDownFeedbackMapperTests.cs

Added feedback component to help confirmation page

EYQB-1146: Added feedback component to help confirmation page

---

src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
tests/Dfe.EarlyYearsQualification.E2ETests/tests/e2e/components/security-header.spec.ts

Updated the csp header

---

src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
tests/Dfe.EarlyYearsQualification.E2ETests/tests/e2e/components/security-header.spec.ts

Update release branch with main

Update release branch with main

---

src/Dfe.EarlyYearsQualification.Caching/DistributedCacheExtensions.cs
tests/Dfe.EarlyYearsQualification.UnitTests/HttpHandlers/CachingHandlerTests.cs

Updated cache timeout
Running locally, unit test and e2e tests

EYQB-1245: Updated cache timeout

---

src/Dfe.EarlyYearsQualification.Caching/Dfe.EarlyYearsQualification.Caching.csproj
src/Dfe.EarlyYearsQualification.Content/Dfe.EarlyYearsQualification.Content.csproj

Updated to latest packages
Run unit & e2e tests

Chore: Updated to latest packages

---

src/Dfe.EarlyYearsQualification.Web/Controllers/ConfirmQualificationController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/HelpController.cs
src/Dfe.EarlyYearsQualification.Web/Controllers/Questions/QuestionsController.Organisation.cs
src/Dfe.EarlyYearsQualification.Web/Services/Notifications/HelpPageNotification.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/HelpFormEnquiry.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/IUserJourneyCookieService.cs
src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ConfirmQualificationControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/HelpControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/GovUkNotifyServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs

Addressed bug which overwrites user's selection of awarding org

---

src/Dfe.EarlyYearsQualification.Content/Entities/QualificationListPage.cs
src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs
src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationListModel.cs
src/Dfe.EarlyYearsQualification.Web/Services/QualificationSearch/QualificationSearchService.cs
src/Dfe.EarlyYearsQualification.Web/Views/QualificationSearch/Get.cshtml
tests/Dfe.EarlyYearsQualification.E2ETests/tests/e2e/pages/qualification-list.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationSearchServiceTests.cs

Initial commit of the new L6 or Not sure content
Running locally, unit test & e2e tests

EYQB-1196: Initial commit of the new L6 or Not sure content

---

src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
tests/Dfe.EarlyYearsQualification.E2ETests/tests/_shared/security-text.spec.ts
tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj

Package updates

---

tests/Dfe.EarlyYearsQualification.E2ETests/tests/_shared/security-text.spec.ts

Updated test to change authentication method

Updated test

---

src/Dfe.EarlyYearsQualification.Web/Security/SecureHeaderConfiguration.cs
src/Dfe.EarlyYearsQualification.Web/wwwroot/js/gtm/form-handler.js
tests/Dfe.EarlyYearsQualification.E2ETests/tests/e2e/components/security-header.spec.ts

Added new GTM events.
Also fixed a security header issue regarding latest govuk package update

EYQB-1278: Added new GTM events
