DFE-Digital/check-an-early-years-qualification

Dfe.EarlyYearsQualification.sln, src/Dfe.EarlyYearsQualification.Content/Dfe.EarlyYearsQualification.Content.csproj, src/Dfe.EarlyYearsQualification.Content/Entities/LandingPage.cs, src/Dfe.EarlyYearsQualification.Content/Renderers/UnorderedListRenderer.cs, src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentService.cs, src/Dfe.EarlyYearsQualification.Content/Services/IContentService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/HomeController.cs, src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj, src/Dfe.EarlyYearsQualification.Web/Models/Content/LandingPageModel.cs, src/Dfe.EarlyYearsQualification.Web/Program.cs, src/Dfe.EarlyYearsQualification.Web/Views/Home/Content.cshtml, src/Dfe.EarlyYearsQualification.Web/appsettings.json
Added initial Contentful setup and dummy models & views to test the integration
=> Added initial Contentful setup

.github/actions/codeql-and-dependency-checks/action.yml, .github/dependabot.yml, .github/workflows/code-pr-check.yml
- Added CodeQL checks to workflow on PR.
- Added dependency check action to PR - Link to action [here](https://github.com/actions/dependency-review-action)
- Added Dependabot settings yaml file
- CodeQL can be seen to be running in this PR.
- Dependabot looks like it will need to be in main to work - might not even be needed?
=> Added yml to run codeql against project

src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs
Also: consistency of return block format.
NB: we should address at some point that `_logger` isn't ever used (...I have the benefit of ReSharper!)
Null `detailsPageContent` was redirecting to unqualified (and therefore erroneous) controller method.
Runs locally, & error page appears if `detailsPageContent` is `null`.
=> Qualify Error redirect with its controller

tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/HealthControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/HomeControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/ViewComponents/FooterLinksViewComponentTests.cs
Swap to FluentAssertions, as agreed by the team.
EYQB-209
All tests pass locally. Pages look OK.
=> Use FluentAssertions

src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml
- Added a CSS class to the main HTML tag.
- It essentially adds the footer colour as the main background color, giving the illusion of the footer filling the bottom of the page!
- Tested locally - see screenshots
- new and existing tests passing
Before:
After:
=> added css to allow 'footer to fill bottom of page'

.github/workflows/build-image.yml, src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj, src/Dfe.EarlyYearsQualification.Web/Program.cs, src/Dfe.EarlyYearsQualification.Web/appsettings.json, src/Dfe.EarlyYearsQualification.Web/set-contentful-secrets.sh
- Contentful secrets are now set in GitHub secrets, and are being pulled in and set in actions dependent on the environment.
- Contentful secrets locally will now be stored in dotnet secrets, I've added a .sh script to help with setting these
https://dfedigital.atlassian.net/browse/EYQB-243
=> Contentful secrets refactor

terraform/modules/azure-web/README.md, terraform/modules/azure-web/web-app.tf
=> EYQB-233: Add reference to slot

src/Dfe.EarlyYearsQualification.Web/Controllers/ChallengeController.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ChallengeControllerTests.cs
Updated to set the HTTPOnly flag on the cookie
=> Updated to set the HTTPOnly flag on the cookie

src/Dfe.EarlyYearsQualification.Content/Constants/AwardingOrganisations.cs, src/Dfe.EarlyYearsQualification.Content/Dfe.EarlyYearsQualification.Content.csproj, src/Dfe.EarlyYearsQualification.Content/Services/ContentfulContentFilterService.cs, src/Dfe.EarlyYearsQualification.Content/Services/FuzzyAdapter.cs, src/Dfe.EarlyYearsQualification.Content/Services/IContentFilterService.cs, src/Dfe.EarlyYearsQualification.Content/Services/IFuzzyAdapter.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulFilterService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QualificationListModel.cs, src/Dfe.EarlyYearsQualification.Web/Models/UserJourneyModel.cs, src/Dfe.EarlyYearsQualification.Web/Program.cs, src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/IUserJourneyCookieService.cs, src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs, src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Get.cshtml, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/urls-to-check.js, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulFilterServiceTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentFilterServiceTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs
Initial commit of the Contentful filter changes for the qualification list.
=> Initial commit of the Contentful filter changes for the qualification list page.

src/Dfe.EarlyYearsQualification.Content/Entities/QualificationListPage.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/FilterModel.cs, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-list-spec.cy.js
Pulled the default headings out into Contentful and mapped them to the model.
Running manually and e2e tests
=> Fix/EYQB-320: Default headings

src/Dfe.EarlyYearsQualification.Content/Constants/AdvicePages.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Constants/Options.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, tests/Dfe.EarlyYearsQualification.AccessibilityTests/.pa11yci-ubuntu.js, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/journey/journey-spec.cy.js, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/advice-spec.cy.js, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/shared/urls-to-check.js, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
- Added new Scotland, Wales and Northern Ireland static advice pages
- Hooked them up to the where qual was awarded page
- Added unit and E2E tests
https://dfedigital.atlassian.net/browse/EYQB-369
https://dfedigital.atlassian.net/browse/EYQB-371
https://dfedigital.atlassian.net/browse/EYQB-372
- Tested manually locally, including back button navigation
- New and existing tests passing
=> New Scotland, Wales and NI advice pages

src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs
Updated to add in the reset functionality when someone starts the first step of the journey. Also, changed the length of the cookie to be 30 minutes.
=> Updated to add in the reset functionality

src/Dfe.EarlyYearsQualification.Content/Entities/DateQuestionPage.cs, src/Dfe.EarlyYearsQualification.Content/Entities/DropdownQuestionPage.cs, src/Dfe.EarlyYearsQualification.Content/Entities/RadioQuestionPage.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/BaseQuestionModel.cs, src/Dfe.EarlyYearsQualification.Web/Models/ErrorSummaryModel.cs, src/Dfe.EarlyYearsQualification.Web/Views/Questions/Date.cshtml, src/Dfe.EarlyYearsQualification.Web/Views/Questions/Dropdown.cshtml, src/Dfe.EarlyYearsQualification.Web/Views/Questions/Radio.cshtml, src/Dfe.EarlyYearsQualification.Web/Views/Shared/Partials/ErrorSummary.cshtml, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/question-spec.cy.js, tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
Added new error summary block to the question pages
Running locally and e2e tests
=> EYQB-479: Added new error summary block to the question pages

content/Dfe.EarlyYearsQualification.ContentUpload/Program.cs, content/Dfe.EarlyYearsQualification.ContentUpload/QualificationUpload.cs, src/Dfe.EarlyYearsQualification.Content/Entities/Qualification.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulFilterService.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/CheckAdditionalRequirementsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ConfirmQualificationControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QualificationDetailsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentFilterServiceTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/ContentfulContentServiceTests.cs
SonarCloud suggestion: these `Qualification` class constructors don't need 10 parameters.
=> Qualification classes use only mandatory fields in constructors.

src/Dfe.EarlyYearsQualification.Content/Entities/DateQuestionPage.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, src/Dfe.EarlyYearsQualification.Web/Helpers/IPlaceholderUpdater.cs, src/Dfe.EarlyYearsQualification.Web/Helpers/PlaceholderUpdater.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/DateQuestionModelValidator.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/IDateQuestionModelValidator.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/ValidationResult.cs, src/Dfe.EarlyYearsQualification.Web/Program.cs, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/question-spec.cy.js, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Helpers/PlaceholderUpdaterTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/DateQuestionModelValidatorTests.cs
Updated logic to add in new error messages for the When was the qualification started page
=> EYQB-500: Updated logic to add in new error messages for the When was the qualification started page

src/Dfe.EarlyYearsQualification.Web/Helpers/AntiForgeryCookieBuilder.cs, src/Dfe.EarlyYearsQualification.Web/Program.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Helpers/AntiForgeryCookieBuilderTests.cs
Added new cookie builder to always set the secure flag on anti forgery token
=> EYQB-516: Added new cookie builder to always set the secure flag

src/Dfe.EarlyYearsQualification.Web/Controllers/AdviceController.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/ConfirmQualificationController.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs, src/Dfe.EarlyYearsQualification.Web/Models/UserJourneyModel.cs, src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/IUserJourneyCookieService.cs, src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/UserJourneyCookieService.cs, src/Dfe.EarlyYearsQualification.Web/Services/UserJourneyCookieService/YesOrNo.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/AdviceControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/UserJourneyCookieServiceTests.cs
Record whether the user selected the qualification from the list, so that the back-link address
can be set correctly if they come through Level 6 advice pages.
EYQB-487
Tested locally; some new unit tests.
=> EYQB-487. Remember whether user selected the qual from the list.

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/DetailsPageModel.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/RatioRequirementModel.cs, src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-details-spec.cy.js, tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
Updated to add in new ratio text when not F&R
=> EYQB-536: Updated to add in new ratio text when not F&R

src/Dfe.EarlyYearsQualification.Web/Controllers/ChallengeController.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ChallengeControllerTests.cs
Users are copying their secret from the invitation email, and sometimes picking up leading or trailing spaces, and this has caused support requests. This PR trims the user's submitted secret before using it.
Tested locally.
=> Trim user's submitted secret value.

src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css
Removed the margin bottom from the p tag in the feedback banner
=> EYQB-656: Removed the margin bottom from the p tag in the feedback banner

content/Dfe.EarlyYearsQualification.ContentUpload/Dfe.EarlyYearsQualification.ContentUpload.csproj, src/Dfe.EarlyYearsQualification.Content/Dfe.EarlyYearsQualification.Content.csproj, src/Dfe.EarlyYearsQualification.Web/Dfe.EarlyYearsQualification.Web.csproj
Contentful content was not being rendered correctly for certain qualifications: for example, missing hyperlink in qualification EYQ-224. Tracked down to a Contentful change, issue was fixed by downgrading Contentful libraries to version 8.0.1.
Ran locally, the missing content was rendered correctly.
=> Downgrade contentful libs to 8.0.1.

src/Dfe.EarlyYearsQualification.Content/Entities/DetailsPage.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QualificationDetailsController.cs, src/Dfe.EarlyYearsQualification.Web/Mappers/QualificationDetailsMapper.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/DetailsPageModel.cs, src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/IQualificationDetailsService.cs, src/Dfe.EarlyYearsQualification.Web/Services/QualificationDetails/QualificationDetailsService.cs, src/Dfe.EarlyYearsQualification.Web/Views/QualificationDetails/Index.cshtml, tests/Dfe.EarlyYearsQualification.E2ETests/cypress/e2e/pages/qualification-details-spec.cy.js, tests/Dfe.EarlyYearsQualification.UnitTests/Dfe.EarlyYearsQualification.UnitTests.csproj, tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/QualificationDetailsMapperTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationDetailsServiceTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/QualificationSearchServiceTests.cs
Initial commit of the new ratios text field
Running locally, unit tests and E2E test
=> Initial commit of the new ratios text field

src/Dfe.EarlyYearsQualification.Content/Entities/DateQuestionPage.cs, src/Dfe.EarlyYearsQualification.Mock/Content/MockContentfulService.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, src/Dfe.EarlyYearsQualification.Web/Mappers/DateQuestionMapper.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/BaseQuestionModel.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/DateQuestionModel.cs, src/Dfe.EarlyYearsQualification.Web/Views/Questions/Date.cshtml, tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/question.spec.ts, tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/DateQuestionMapperTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Mocks/MockContentfulServiceTests.cs
Added new a new postheader block to the date page along with a hint header. These together allow for the changes required in the ticket to be handled via contentful and be customisable for other pages with limited adjustments
https://dfedigital.atlassian.net/browse/EYQB-789
manual testing, unit tests extended and passing and e2e tests extended and passing
=> feature: added post content and hint header blocks to date question

src/Dfe.EarlyYearsQualification.Web/Controllers/ChallengeController.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/ChallengeControllerTests.cs
In case people have bookmarked the challenge page, make it redirect to the start page if service instance is configured for public access.
Ad hoc change. Ticket will be created.
New unit test. Checked locally, with public access configured on and off.
=> Challenge page redirects to start page if public

src/Dfe.EarlyYearsQualification.Web/Controllers/QuestionsController.cs, src/Dfe.EarlyYearsQualification.Web/Mappers/DateQuestionMapper.cs, src/Dfe.EarlyYearsQualification.Web/Mappers/DatesQuestionMapper.cs, src/Dfe.EarlyYearsQualification.Web/Models/BannerError.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/DateQuestionModel.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/DateQuestionModelValidator.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/QuestionModels/Validators/DateValidationResult.cs, src/Dfe.EarlyYearsQualification.Web/Models/FieldId.cs, tests/Dfe.EarlyYearsQualification.E2ETests/tests/pages/question.spec.ts, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/QuestionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Mappers/DateQuestionMapperTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/DateQuestionModelValidatorTests.cs
Added ability for date errors to have independent links
Not particularly happy with the need to convert to string and back on the new enum but to change that will require a more significant rewrite of questionsController which I feel is out of scope for this ticket
Manual testing and unit tests and e2e tests
=> fix: split date banner errors so links can work independently

src/Dfe.EarlyYearsQualification.Caching/CachingHandler.cs, src/Dfe.EarlyYearsQualification.Caching/CachingOption.cs, src/Dfe.EarlyYearsQualification.Caching/Interfaces/ICachingOptionsManager.cs, src/Dfe.EarlyYearsQualification.Web/Controllers/OptionsController.cs, src/Dfe.EarlyYearsQualification.Web/Models/Content/OptionsPageModel.cs, src/Dfe.EarlyYearsQualification.Web/Models/OptionsPageModel.cs, src/Dfe.EarlyYearsQualification.Web/Services/Caching/CachingOptionsManager.cs, src/Dfe.EarlyYearsQualification.Web/Services/Caching/NeverBypassCacheManager.cs, src/Dfe.EarlyYearsQualification.Web/Services/Caching/SetupExtensions.cs, src/Dfe.EarlyYearsQualification.Web/ViewComponents/OptionsIndicatorViewComponent.cs, src/Dfe.EarlyYearsQualification.Web/Views/Options/Index.cshtml, src/Dfe.EarlyYearsQualification.Web/Views/Shared/Components/OptionsIndicator/Default.cshtml, src/Dfe.EarlyYearsQualification.Web/Views/Shared/_Layout.cshtml, src/Dfe.EarlyYearsQualification.Web/wwwroot/css/site.css, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/OptionsControllerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/HttpHandlers/CachingHandlerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/CachingOptionsManagerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Services/NeverBypassCacheManagerTests.cs, tests/Dfe.EarlyYearsQualification.UnitTests/ViewComponents/OptionsIndicatorViewComponentTests.cs
A new options page, on which is the ability for the user to bypass the Contentful cache. This will never be enabled in production.
To do:
* In production, disable the `/options` page. **DONE**
* In production, set up the `NeverBypassCache` service **DONE**
* Make the `/options` page "select and continue" button go to the start page after setting the option **DONE**
* Add indicator if option selected is any other than the default "production-like" behaviour option **DONE**
EYQB-986
Tested locally, and in `dev`.
=> Added ability for user to set service to bypass the cache

src/Dfe.EarlyYearsQualification.Web/Controllers/CacheController.cs, tests/Dfe.EarlyYearsQualification.UnitTests/Controllers/CacheControllerTests.cs
Anti-forgery not required for API `POST` calls.
Tested in `dev` and `staging`.
=> Anti-forgery not needed for API posts

terraform/README.md, terraform/main.tf, terraform/modules/azure-network/README.md, terraform/modules/azure-network/key-vault.tf, terraform/modules/azure-network/outputs.tf, terraform/modules/azure-network/variables.tf, terraform/variables.tf
The education.gov.uk domain is no longer in use by the service, so we are removing the associated infrastructure.
The custom domain was deleted in phase 1 (#605).
This is phase 2: deletion of the certificate.
EYQB-1022
Tested in `dev` and `staging` environments before going to production.
=> Delete redundant Key Vault certificate
